### ISSUE TITLE
Adicionar o projeto Diciotech e o projeto Mulheres na Tecnologia

### ISSUE THREAD

**Issue by morgannadev** [bugelseif/projetos-iniciantes#44]
Olá, gostaria de contribuir com o projeto trazendo esses dois mencionados:

- [Diciotech](https://github.com/levxyca/diciotech/);
- [Mulheres na Tecnologia](https://github.com/morgannadev/mulherestecnologia).

Se aceito, por favor, pode atribuir essa issue a mim? Obrigada!

**Comment by bugelseif** [comment]
Assinada, LGTM.
